trigger:
  branches:
    include:
      - main  # to trigger this pipeline on changes to 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Setting up SSH key"
    mkdir -p ~/.ssh
    echo "$GITHUB_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan github.com >> ~/.ssh/known_hosts

    echo "Adding GitHub remote"
    git remote add github git@github.com:marsdensoftware/sep-aem-ui.git

    echo "Pull the latest from ADO main branch"
    git fetch origin main
    git checkout origin/main

    echo "Push to GitHub main branch"
    git push -u github main
  displayName: 'Push Code to GitHub'
  env:
    GITHUB_SSH_PRIVATE_KEY: $(GITHUB_SSH_PRIVATE_KEY)