trigger:
  branches:
    include:
      - main  # to trigger this pipeline on changes to 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    
    echo "Adding GitHub remote"
    git remote add github https://$(GITHUB_PAT)@github.com:marsdensoftware/sep-aem-ui.git
    git push github $(Build.SourceBranchName):$(Build.SourceBranchName) --force

  displayName: 'Push Code to GitHub'
  env:
    GITHUB_SSH_PRIVATE_KEY: $(GITHUB_SSH_PRIVATE_KEY)